export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";

export const QUESTION_SAVE_REQUEST = "QUESTION_SAVE_REQUEST";
export const QUESTION_SAVE_SUCCESS = "QUESTION_SAVE_SUCCESS";
export const QUESTION_SAVE_FAIL = "QUESTION_SAVE_FAIL";

export const QUESTION_DETAIL_REQUEST = "QUESTION_DETAIL_REQUEST";
export const QUESTION_DETAIL_SUCCESS = "QUESTION_DETAIL_SUCCESS";
export const QUESTION_DETAIL_FAIL = "QUESTION_DETAIL_FAIL";